version: '3.8'

services:
  mysql:
    image: mysql:8.0-bookworm
    container_name: mysql-server
    env_file: 
        - .env
    ports:
      - "3306:3306"
    volumes:
      - /data/mysqldata:/var/lib/mysql
    restart: always
